### ISSUE TITLE
In Django application, '/metrics' unaccessible when using Unix Domain Sockets 

### ISSUE THREAD

**Issue by Antsthebul** [prometheus/client_python#926]
Im using the `django_prometheus` library which is a wrapper for `prometheus_client` library for my  Django app. I am not running Prometheus, (or the entire applcaition in a Docker container), which might be part of my problem, though I dont see why this would be a requirement. The Django application is bound to Unix Domain Sockets,. NGINX is listening on default port 80 and re-routes traffic with the proxy_pass header. 

NGINX
```
server {
    server_name hotname www.hostname ip;

[...]
    location /metrics{

        proxy_pass http://<unix_domain_socket>;
    }

    location / {
        proxy_pass http://unix:<unix_domain_socket>;
        
}
```
## prometheus
```
<default prom config>
[...]
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django-app"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost] # nothing works (IP, etc..) and prometheus attempts to use port 80 with a predefined scheme of http://

  - job_name: "node"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9100"]
```

## Solution
By removing the unix domain socket  in NGINX and going back to TCP/IP that gunicorn uses by default, Prometheus was able to successfully pickup metrics from `/metrics`

Is there something Im missing? I feel like the only other options are changing the whole infrastructure ( to docker), or try and use a log based-metrics. Kinda stinks not being able to utilize Unix Sockets at a cost for wants to monitor the application. 

Even though Im using
